# Generated by Django 4.0.3 on 2022-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
